int =2
print(int,type(int),"\n")
a=22.4
print(a,type(a),"\n")
c="bhavya"
print(c,type(c),"\n")
d=True
print(d,type(d),"\n")
e=["ramesh",2]
e.append("sushma")
print(e,"\n")
e.insert(0,"bhavesh")
print(e,"\n")
e.pop(1)
print(e)
print(e,type(e),"\n")
f=("ramesh",2,"ramesh")
print(f,type(f),"\n")
g={"name":"Bhavya","surname":"Modh"}
print(g["name"])
print(g["surname"])
